 /* ==========================================================
 * bootstrap-formhelpers-currencies.en_US.js
 * https://github.com/vlamanna/BootstrapFormHelpers
 * ==========================================================
 * Copyright 2013 Vincent Lamanna
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ========================================================== */
var BFHCurrenciesList = {
'AED':{'label':'United Arab Emirates dirham','currencyflag':'','symbol':'د.إ','code':'AED'},
'AFN':{'label':'Afghan afghani','currencyflag':'','symbol':'؋','code':'AFN'},
'ALL':{'label':'Albanian lek','currencyflag':'','symbol':'L','code':'ALL'},
'AMD':{'label':'Armenian dram','currencyflag':'','symbol':'դր','code':'AMD'},
'AOA':{'label':'Angolan kwanza','currencyflag':'','symbol':'Kz','code':'AOA'},
'ARS':{'label':'Argentine peso','currencyflag':'','symbol':'$','code':'ARS'},
'AUD':{'label':'Australian dollar','currencyflag':'','symbol':'$','code':'AUD'},
'AWG':{'label':'Aruban florin','currencyflag':'','symbol':'ƒ','code':'AWG'},
'AZN':{'label':'Azerbaijani manat','currencyflag':'','symbol':'','code':'AZN'},
'BAM':{'label':'Bosnia and Herzegovina convertible mark','currencyflag':'','symbol':'KM','code':'BAM'},
'BBD':{'label':'Barbadian dollar','currencyflag':'','symbol':'$','code':'BBD'},
'BDT':{'label':'Bangladeshi taka','currencyflag':'','symbol':'৳','code':'BDT'},
'BGN':{'label':'Bulgarian lev','currencyflag':'','symbol':'лв','code':'BDT'},
'BHD':{'label':'Bahraini dinar','currencyflag':'','symbol':'.د.ب','code':'BHD'},
'BIF':{'label':'Burundian franc','currencyflag':'','symbol':'Fr','code':'BIF'},
'BMD':{'label':'Bermudian dollar','currencyflag':'','symbol':'$','code':'BMD'},
'BND':{'label':'Brunei dollar','currencyflag':'','symbol':'$','code':'BND'},
'BOB':{'label':'Bolivian boliviano','currencyflag':'','symbol':'Bs','code':'BOB'},
'BRL':{'label':'Brazilian real','currencyflag':'','symbol':'R$','code':'BRL'},
'BSD':{'label':'Bahamian dollar','currencyflag':'','symbol':'$','code':'BSD'},
'BTN':{'label':'Bhutanese ngultrum','currencyflag':'','symbol':'Nu','code':'BTN'},
'BWP':{'label':'Botswana pula','currencyflag':'','symbol':'P','code':'BWP'},
'BYR':{'label':'Belarusian ruble','currencyflag':'','symbol':'Br','code':'BYR'},
'BZD':{'label':'Belize dollar','currencyflag':'','symbol':'$','code':'BZD'},
'CAD':{'label':'Canadian dollar','currencyflag':'','symbol':'$','code':'CAD'},
'CDF':{'label':'Congolese franc','currencyflag':'','symbol':'Fr','code':'CDF'},
'CHF':{'label':'Swiss franc','currencyflag':'','symbol':'Fr','code':'CHF'},
'CLP':{'label':'Chilean peso','currencyflag':'','symbol':'$','code':'CLP'},
'CNY':{'label':'Chinese yuan','currencyflag':'','symbol':'¥','code':'CNY'},
'COP':{'label':'Colombian peso','currencyflag':'','symbol':'$','code':'COP'},
'CRC':{'label':'Costa Rican colón','currencyflag':'','symbol':'₡','code':'CRC'},
'CUP':{'label':'Cuban convertible peso','currencyflag':'','symbol':'$','code':'CUP'},
'CVE':{'label':'Cape Verdean escudo','currencyflag':'','symbol':'$','code':'CVE'},
'CZK':{'label':'Czech koruna','currencyflag':'','symbol':'Kč','code':'CZK'},
'DJF':{'label':'Djiboutian franc','currencyflag':'','symbol':'Fr','code':'DJF'},
'DKK':{'label':'Danish krone','currencyflag':'','symbol':'kr','code':'DKK'},
'DOP':{'label':'Dominican peso','currencyflag':'','symbol':'$','code':'DOP'},
'DZD':{'label':'Algerian dinar','currencyflag':'','symbol':'د.ج','code':'DZD'},
'EGP':{'label':'Egyptian pound','currencyflag':'','symbol':'ج.م','code':'EGP'},
'ERN':{'label':'Eritrean nakfa','currencyflag':'','symbol':'Nfk','code':'ERN'},
'ETB':{'label':'Ethiopian birr','currencyflag':'','symbol':'Br','code':'ETB'},
'EUR':{'label':'Euro','currencyflag':'','symbol':'€','code':'EUR'},
'FJD':{'label':'Fijian dollar','currencyflag':'','symbol':'$','code':'FJD'},
'FKP':{'label':'Falkland Islands pound','currencyflag':'FI','symbol':'£','code':'FKP'},
'GBP':{'label':'British pound','currencyflag':'','symbol':'£','code':'GBP'},
'GEL':{'label':'Georgian lari','currencyflag':'','symbol':'ლ','code':'GEL'},
'GHS':{'label':'Ghana cedi','currencyflag':'','symbol':'₵','code':'GHS'},
'GMD':{'label':'Gambian dalasi','currencyflag':'','symbol':'D','code':'GMD'},
'GNF':{'label':'Guinean franc','currencyflag':'','symbol':'Fr','code':'GNF'},
'GTQ':{'label':'Guatemalan quetzal','currencyflag':'','symbol':'Q','code':'GTQ'},
'GYD':{'label':'Guyanese dollar','currencyflag':'','symbol':'$','code':'GYD'},
'HKD':{'label':'Hong Kong dollar','currencyflag':'','symbol':'$','code':'HKD'},
'HNL':{'label':'Honduran lempira','currencyflag':'','symbol':'L','code':'HNL'},
'HRK':{'label':'Croatian kuna','currencyflag':'','symbol':'kn','code':'HRK'},
'HTG':{'label':'Haitian gourde','currencyflag':'','symbol':'G','code':'HTG'},
'HUF':{'label':'Hungarian forint','currencyflag':'','symbol':'Ft','code':'HUF'},
'IDR':{'label':'Indonesian rupiah','currencyflag':'','symbol':'Rp','code':'IDR'},
'ILS':{'label':'Israeli new shekel','currencyflag':'','symbol':'₪','code':'ILS'},
'IMP':{'label':'Manx pound','currencyflag':'','symbol':'£','code':'IMP'},
'INR':{'label':'Indian rupee','currencyflag':'','symbol':'','code':'INR'},
'IQD':{'label':'Iraqi dinar','currencyflag':'','symbol':'ع.د','code':'IQD'},
'IRR':{'label':'Iranian rial','currencyflag':'','symbol':'﷼','code':'IRR'},
'ISK':{'label':'Icelandic króna','currencyflag':'','symbol':'kr','code':'ISK'},
'JEP':{'label':'Jersey pound','currencyflag':'','symbol':'£','code':'JEP'},
'JMD':{'label':'Jamaican dollar','currencyflag':'','symbol':'$','code':'JMD'},
'JOD':{'label':'Jordanian dinar','currencyflag':'','symbol':'د.ا','code':'JOD'},
'JPY':{'label':'Japanese yen','currencyflag':'','symbol':'¥','code':'JPY'},
'KES':{'label':'Kenyan shilling','currencyflag':'','symbol':'Sh','code':'KES'},
'KGS':{'label':'Kyrgyzstani som','currencyflag':'','symbol':'лв','code':'KGS'},
'KHR':{'label':'Cambodian riel','currencyflag':'','symbol':'៛','code':'KHR'},
'KMF':{'label':'Comorian franc','currencyflag':'','symbol':'Fr','code':'KMF'},
'KPW':{'label':'North Korean won','currencyflag':'','symbol':'₩','code':'KPW'},
'KRW':{'label':'South Korean won','currencyflag':'','symbol':'₩','code':'KRW'},
'KWD':{'label':'Kuwaiti dinar','currencyflag':'','symbol':'د.ك','code':'KWD'},
'KYD':{'label':'Cayman Islands dollar','currencyflag':'','symbol':'$','code':'KYD'},
'KZT':{'label':'Kazakhstani tenge','currencyflag':'','symbol':'KZT','code':'KZT'},
'LAK':{'label':'Lao kip','currencyflag':'','symbol':'₭','code':'LAK'},
'LBP':{'label':'Lebanese pound','currencyflag':'','symbol':'ل.ل','code':'LBP'},
'LKR':{'label':'Sri Lankan rupee','currencyflag':'','symbol':'Rs','code':'LKR'},
'LRD':{'label':'Liberian dollar','currencyflag':'','symbol':'$','code':'LRD'},
'LSL':{'label':'Lesotho loti','currencyflag':'','symbol':'L','code':'LSL'},
'LTL':{'label':'Lithuanian litas','currencyflag':'','symbol':'Lt','code':'LTL'},
'LVL':{'label':'Latvian lats','currencyflag':'','symbol':'Ls','code':'LVL'},
'LYD':{'label':'Libyan dinar','currencyflag':'','symbol':'ل.د','code':'LYD'},
'MAD':{'label':'Moroccan dirham','currencyflag':'','symbol':'د.م.','code':'MAD'},
'MDL':{'label':'Moldovan leu','currencyflag':'','symbol':'L','code':'MDL'},
'MGA':{'label':'Malagasy ariary','currencyflag':'','symbol':'Ar','code':'MGA'},
'MKD':{'label':'Macedonian denar','currencyflag':'','symbol':'ден','code':'MKD'},
'MMK':{'label':'Burmese kyat','currencyflag':'','symbol':'Ks','code':'MMK'},
'MNT':{'label':'Mongolian tögrög','currencyflag':'','symbol':'₮','code':'MNT'},
'MOP':{'label':'Macanese pataca','currencyflag':'','symbol':'P','code':'MOP'},
'MRO':{'label':'Mauritanian ouguiya','currencyflag':'','symbol':'UM','code':'MRO'},
'MUR':{'label':'Mauritian rupee','currencyflag':'','symbol':'Rs','code':'MUR'},
'MVR':{'label':'Maldivian rufiyaa','currencyflag':'','symbol':'Rf','code':'MVR'},
'MWK':{'label':'Malawian kwacha','currencyflag':'','symbol':'MK','code':'MWK'},
'MXN':{'label':'Mexican peso','currencyflag':'','symbol':'$','code':'MXN'},
'MYR':{'label':'Malaysian ringgit','currencyflag':'','symbol':'MR','code':'MYR'},
'MZN':{'label':'Mozambican metical','currencyflag':'','symbol':'MT','code':'MZN'},
'NAD':{'label':'Namibian dollar','currencyflag':'','symbol':'$','code':'NAD'},
'NGN':{'label':'Nigerian naira','currencyflag':'','symbol':'₦','code':'NGN'},
'NIO':{'label':'Nicaraguan córdoba','currencyflag':'','symbol':'C$','code':'NIO'},
'NOK':{'label':'Norwegian krone','currencyflag':'','symbol':'kr','code':'NOK'},
'NPR':{'label':'Nepalese rupee','currencyflag':'','symbol':'Rs','code':'NPR'},
'NZD':{'label':'New Zealand dollar','currencyflag':'','symbol':'$','code':'NZD'},
'OMR':{'label':'Omani rial','currencyflag':'','symbol':'ر.ع.','code':'OMR'},
'PAB':{'label':'Panamanian balboa','currencyflag':'','symbol':'B/.','code':'PAB'},
'PEN':{'label':'Peruvian nuevo sol','currencyflag':'','symbol':'S/.','code':'PEN'},
'PGK':{'label':'Papua New Guinean kina','currencyflag':'','symbol':'K','code':'PGK'},
'PHP':{'label':'Philippine peso','currencyflag':'','symbol':'₱','code':'PHP'},
'PKR':{'label':'Pakistani rupee','currencyflag':'','symbol':'Rs','code':'PKR'},
'PLN':{'label':'Polish złoty','currencyflag':'','symbol':'zł','code':'PLN'},
'PRB':{'label':'Transnistrian ruble','currencyflag':'','symbol':'р.','code':'PRB'},
'PYG':{'label':'Paraguayan guaraní','currencyflag':'','symbol':'₲','code':'PYG'},
'QAR':{'label':'Qatari riyal','currencyflag':'','symbol':'ر.ق','code':'QAR'},
'RON':{'label':'Romanian leu','currencyflag':'','symbol':'L','code':'RON'},
'RSD':{'label':'Serbian dinar','currencyflag':'','symbol':'дин','code':'RSD'},
'RUB':{'label':'Russian ruble','currencyflag':'','symbol':'руб.','code':'RUB'},
'RWF':{'label':'Rwandan franc','currencyflag':'','symbol':'Fr','code':'RWF'},
'SAR':{'label':'Saudi riyal','currencyflag':'','symbol':'ر.س','code':'SAR'},
'SBD':{'label':'Solomon Islands dollar','currencyflag':'','symbol':'$','code':'SBD'},
'SCR':{'label':'Seychellois rupee','currencyflag':'','symbol':'Rs','code':'SCR'},
'SDG':{'label':'Singapore dollar','currencyflag':'','symbol':'$','code':'SDG'},
'SEK':{'label':'Swedish krona','currencyflag':'','symbol':'kr','code':'SEK'},
'SGD':{'label':'Singapore dollar','currencyflag':'','symbol':'$','code':'SGD'},
'SHP':{'label':'Saint Helena pound','currencyflag':'','symbol':'£','code':'SHP'},
'SLL':{'label':'Sierra Leonean leone','currencyflag':'','symbol':'Le','code':'SLL'},
'SOS':{'label':'Somali shilling','currencyflag':'','symbol':'Sh','code':'SOS'},
'SRD':{'label':'Surinamese dollar','currencyflag':'','symbol':'$','code':'SRD'},
'SSP':{'label':'South Sudanese pound','currencyflag':'','symbol':'£','code':'SSP'},
'STD':{'label':'São Tomé and Príncipe dobra','currencyflag':'','symbol':'Db','code':'STD'},
'SVC':{'label':'Salvadoran colón','currencyflag':'','symbol':'₡','code':'SVC'},
'SYP':{'label':'Syrian pound','currencyflag':'','symbol':'£','code':'SYP'},
'SZL':{'label':'Swazi lilangeni','currencyflag':'','symbol':'L','code':'SZL'},
'THB':{'label':'Thai baht','currencyflag':'','symbol':'฿','code':'THB'},
'TJS':{'label':'Tajikistani somoni','currencyflag':'','symbol':'SM','code':'TJS'},
'TMT':{'label':'Turkmenistan manat','currencyflag':'','symbol':'m','code':'TMT'},
'TND':{'label':'Tunisian dinar','currencyflag':'','symbol':'د.ت','code':'TND'},
'TOP':{'label':'Tongan paʻanga','currencyflag':'','symbol':'T$','code':'TOP'},
'TRY':{'label':'Turkish lira','currencyflag':'','symbol':'','code':'TRY'},
'TTD':{'label':'Trinidad and Tobago dollar','currencyflag':'','symbol':'$','code':'TTD'},
'TWD':{'label':'New Taiwan dollar','currencyflag':'','symbol':'$','code':'TWD'},
'TZS':{'label':'Tanzanian shilling','currencyflag':'','symbol':'Sh','code':'TZS'},
'UAH':{'label':'Ukrainian hryvnia','currencyflag':'','symbol':'₴','code':'UAH'},
'UGX':{'label':'Ugandan shilling','currencyflag':'','symbol':'Sh','code':'UGX'},
'USD':{'label':'United States dollar','currencyflag':'','symbol':'$','code':'USD'},
'UYU':{'label':'Uruguayan peso','currencyflag':'','symbol':'$','code':'UYU'},
'UZS':{'label':'Uzbekistani som','currencyflag':'','symbol':'лв','code':'UZS'},
'VEF':{'label':'Venezuelan bolívar','currencyflag':'','symbol':'Bs F','code':'VEF'},
'VND':{'label':'Vietnamese đồng','currencyflag':'','symbol':'₫','code':'VND'},
'VUV':{'label':'Vanuatu vatu','currencyflag':'','symbol':'Vt','code':'VUV'},
'WST':{'label':'Samoan tālā','currencyflag':'','symbol':'T','code':'WST'},
'XAF':{'label':'Central African CFA franc','currencyflag':'','symbol':'Fr','code':'XAF'},
'XCD':{'label':'East Caribbean dollar','currencyflag':'','symbol':'$','code':'XCD'},
'XOF':{'label':'West African CFA franc','currencyflag':'','symbol':'Fr','code':'XOF'},
'XPF':{'label':'CFP franc','currencyflag':'','symbol':'Fr','code':'XPF'},
'YER':{'label':'Yemeni rial','currencyflag':'','symbol':'﷼','code':'YER'},
'ZAR':{'label':'South African rand','currencyflag':'','symbol':'R','code':'ZAR'},
'ZMW':{'label':'Zambian kwacha','currencyflag':'','symbol':'ZK','code':'ZMW'},
'ZWL':{'label':'Zimbabwean dollar','currencyflag':'','symbol':'$','code':'ZWL'}
}